# Generated by Django 4.0.6 on 2022-07-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('kind', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
