"""upgrade product name length

Revision ID: 7170ad388ef3
Revises: db61642e55b4
Create Date: 2022-06-08 20:32:01.127135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7170ad388ef3"
down_revision = "db61642e55b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "name",
        existing_type=sa.VARCHAR(length=120),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "product",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=120),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
