"""create column created_at to table users

Revision ID: 02d7eed4f8b1
Revises: be6610ecd189
Create Date: 2022-05-22 23:42:15.887002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02d7eed4f8b1"
down_revision = "be6610ecd189"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
