# Generated by Django 4.0.6 on 2022-07-05 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0005_animal_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalDetail",
            fields=[
                (
                    "animal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="animals.animal",
                    ),
                ),
                ("biography", models.TextField(blank=True)),
            ],
        ),
    ]
