# Generated by Django 4.0.6 on 2022-07-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0002_rename_animals_animal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animal",
            name="kind",
        ),
    ]
