"""create column is_staff to table users

Revision ID: be6610ecd189
Revises: 49b39c850518
Create Date: 2022-05-22 23:32:40.287758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "be6610ecd189"
down_revision = "49b39c850518"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_staff", sa.Boolean(), server_default="FALSE", nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_staff")
    # ### end Alembic commands ###
