version: "3"

services:
  pg:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
        - pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"

volumes:
  pg-data: