"""updated username column type with length 100

Revision ID: 2ee877dabca4
Revises: 37d6748c0cec
Create Date: 2022-05-26 13:50:51.610019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2ee877dabca4"
down_revision = "37d6748c0cec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "username",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
