"""add token field to users table

Revision ID: 37d6748c0cec
Revises: 19e32893a051
Create Date: 2022-05-25 21:33:09.470298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37d6748c0cec"
down_revision = "19e32893a051"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("token", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "token")
    # ### end Alembic commands ###
