# Generated by Django 4.0.6 on 2022-07-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_animalfood_options_animal__created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalkind',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
